### ISSUE TITLE
Need in ability bypass proxy for regions other than China 

### ISSUE THREAD

**Issue by shperrung** [samuelhbne/proxy-xray#2]
Hi!
Could you please add RU region for direct connection bypass proxy? CN is defined in run.sh 
Substitution "ru" instead "cn" in "docker run..." cause error in run.sh

**Comment by samuelhbne** [comment]
Hi @shperrung 

Could you please try the following options and share the results? Thanks.

**--domain-direct geosite:ru --ip-direct geoip:ru**

**Comment by shperrung** [comment]
It says me in docker logs that:
```
Xray 1.8.9 (Xray, Penetrates Everything.) Custom (go1.22.1 linux/arm64)
A unified platform for anti-censorship.
2024/03/24 16:14:35 [Info] infra/conf/serial: Reading config: /tmp/proxy-xray.json
Failed to start: main: failed to load config files: [/tmp/proxy-xray.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:ru > infra/conf: failed to load geosite: RU > infra/conf: list not found in geosite.dat: RU
```

Another problem is absense of "VLESS + XTLS-Reality" among clients configs. I already use 3X-UI panel and "VLESS + XTLS-Reality" on 443 port. Another vless on 443 port is impossible. 

Upd. 
I solved my issue
v2rayNG app on mobile allows to export full config.json for "x-ray - client" suitable for Linux.
I created VM Debian and installed x-ray into host. config.json from v2rayNG makes x-ray as "client" with minimal updates. It already has good "inbound" section (local SOCKS and HTTP proxies) and fully completed with client's credentials outbound section.

**Comment by samuelhbne** [comment]
It looked geosite:ru was not supported by v2ray-rules-dat so far. However, you still can bypass Russian IP access by the following options:

**--ip-direct geoip:ru**
